---
src_vocab: '/data/jeicy/data/100w_chinese.vocab'
dst_vocab: '/data/jeicy/data/100w_english.vocab'
src_vocab_size: 40000
dst_vocab_size: 40000
hidden_units: 128
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
binding_embedding: False
gan_iter_num: 50
gan_gen_iter_num: 1
gan_dis_iter_num: 1
generate_num: 5000
rollnum: 20
bias_num: 0.6
logdir: 'gan.log'

train:
    devices: '0'
    src_path: '/data/jeicy/data/train/train/train_jieba_100w.zh'
    dst_path: '/data/jeicy/data/train/train/train_split_100w.en'
    tokens_per_batch:  2500
    max_length: 50
    num_epochs: 50
    logdir: 'gan.log'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5
    optimizer: 'adam_decay'
    learning_rate: 0.00005
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
    batch_size: 50
    shared_embedding: False

generator:
    src_vocab: '/data/jeicy/data/100w_chinese.vocab'
    dst_vocab: '/data/jeicy/data/100w_english.vocab'
    devices: '0'
    src_path: '/data/jeicy/data/train/train/train_jieba_100w.zh'
    dst_path: '/data/jeicy/data/train/train/train_split_100w.en'
    tokens_per_batch:  2500
    max_length: 50
    num_epochs: 50
    logdir: 'gan.log'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5
    optimizer: 'rmsprop'
    modelFile: '/data/jeicy/_NMT_GAN/pre.gen.log/model_epoch_14_step_66000'
    learning_rate: 0.00001
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
    batch_size: 50
    teacher_forcing: True

discriminator:
    dis_src_vocab: '/data/jeicy/data/100w_chinese.vocab.pkl'
    dis_dst_vocab: '/data/jeicy/data/100w_english.vocab.pkl'
    dis_max_epoches: 50
    dis_dispFreq: 1
    dis_saveFreq: 100
    dis_devFreq: 100
    dis_batch_size: 50
    dis_saveto: '/data/jeicy/_NMT_GAN/pre.dis.log/discriminator'
    dis_reshuffle: True
    dis_gpu_devices: 'gpu-0'
    dis_max_len: 50
    dis_positive_data: '/data/jeicy/data/gan/dis_positive_data'
    dis_negative_data: '/data/jeicy/data/gan/dis_negative_data'
    dis_source_data: '/data/jeicy/data/gan/dis_source_data'
    dis_dev_positive_data: '/data/jeicy/data/eval/eval/valid.en-zh_split.en'
    dis_dev_negative_data: '/data/jeicy/data/eval/eval/evaluate_100w.output'
    dis_dev_source_data: '/data/jeicy/data/eval/eval/valid.en-zh_jieba.zh'
    dis_reload: True
    dis_clip_c: 1.0
    dis_dim_word: 128
    dis_optimizer: 'rmsprop'
    dis_scope: 'discnn'
