src_vocab: '/data/jeicy/data/ec-sjtu/en.vocab'
dst_vocab: '/data/jeicy/data/ec-sjtu/zh.vocab'
train:
    src_path: '/data/jeicy/data/ec-sjtu/train/NEU_newsdev2017-src'
    dst_path: '/data/jeicy/data/ec-sjtu/train/NEU_newsdev2017-ref'