---
src_vocab: '/data/jeicy/data/ec-sjtu/en.vocab'
dst_vocab: '/data/jeicy/data/ec-sjtu/zh.vocab'
src_vocab_size: 40000
dst_vocab_size: 40000
hidden_units: 128
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
binding_embedding: False
train:
    devices: '0'
    src_path: '/data/jeicy/data/ec-sjtu/train/NEU_newsdev2017-src'
    dst_path: '/data/jeicy/data/ec-sjtu/train/NEU_newsdev2017-ref'
    tokens_per_batch:  2500
    max_length: 50
    num_epochs: 200
    logdir: 'news.pre.gen.log'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5
    optimizer: 'adam_decay'
    learning_rate: 0.00005
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
    batch_size: 50
    shared_embedding: False

test:
    src_path: '/data/jeicy/data/ec-sjtu/dev/CWMT2017-ec-news-test_split.en'
    dst_path: '/data/jeicy/data/ec-sjtu/dev/CWMT2017-ec-news-test_jieba.zh'
    ori_dst_path: '/data/jeicy/data/ec-sjtu/dev/CWMT2017-ec-news-test_jieba.zh'
    output_path: '/data/jeicy/data/ec-sjtu/dev/evaluate.output'
    batch_size: 100
    max_target_length: 200
    beam_size: 4
    lp_alpha: 0.6
    devices: '0'
