src_vocab: '/data/jeicy/data/100w_chinese.vocab'
dst_vocab: '/data/jeicy/data/100w_english.vocab'
train:
    src_path: '/data/jeicy/data/train/train/train_jieba_100w.zh'
    dst_path: '/data/jeicy/data/train/train/train_split_100w.en'