src_vocab: '/data/jeicy/data/chinese.vocab'
dst_vocab: '/data/jeicy/data/english.vocab'
train:
    src_path: '/data/jeicy/data/train/train/train_jieba.zh'
    dst_path: '/data/jeicy/data/train/train/train_split.en'