src_vocab: '/data/jeicy/data/300w_chinese.vocab'
dst_vocab: '/data/jeicy/data/300w_english.vocab'
train:
    src_path: '/data/jeicy/data/train/train/300w_train_jieba.zh'
    dst_path: '/data/jeicy/data/train/train/300w_train_split.en'