---
src_vocab: '/data/jeicy/data/10w_chinese.vocab'
dst_vocab: '/data/jeicy/data/10w_english.vocab'
src_vocab_size: 47141
dst_vocab_size: 36939
hidden_units: 128
scale_embedding: True
attention_dropout_rate: 0.0
residual_dropout_rate: 0.1
num_blocks: 6
num_heads: 8
binding_embedding: False
train:
    devices: '0'
    src_path: '/data/jeicy/data/train/train/10w1_train_jieba.zh'
    out_path: '/data/jeicy/data/generate/10w1_negative.en'
    tokens_per_batch:  2500
    max_length: 50
    num_epochs: 1
    logdir: 'generate.samples.log'
    save_freq: 1000
    summary_freq: 100
    grads_clip: 5.0
    optimizer: 'adam_decay'
    learning_rate: 0.00005
    learning_rate_warmup_steps: 4000
    label_smoothing: 0.1
    batch_size: 50
    shared_embedding: False
    modelFile: '/data/jeicy/10w/_NMT_GAN/pre.gen.log_10w/model_epoch_198_step_73000'
generator:
    learning_rate: 0.00001
